// Code generated by protoc-gen-go. DO NOT EDIT.
// source: go_grpc_eg.proto

/*
Package go_grpc_eg is a generated protocol buffer package.

It is generated from these files:
	go_grpc_eg.proto

It has these top-level messages:
	Int64
*/
package go_grpc_eg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Int64 struct {
	Value int64 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *Int64) Reset()                    { *m = Int64{} }
func (m *Int64) String() string            { return proto.CompactTextString(m) }
func (*Int64) ProtoMessage()               {}
func (*Int64) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Int64) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*Int64)(nil), "go_grpc_eg.Int64")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Greeter service

type GreeterClient interface {
	CalculateSquare(ctx context.Context, in *Int64, opts ...grpc.CallOption) (*Int64, error)
	CalculateCube(ctx context.Context, in *Int64, opts ...grpc.CallOption) (*Int64, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) CalculateSquare(ctx context.Context, in *Int64, opts ...grpc.CallOption) (*Int64, error) {
	out := new(Int64)
	err := grpc.Invoke(ctx, "/go_grpc_eg.Greeter/CalculateSquare", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) CalculateCube(ctx context.Context, in *Int64, opts ...grpc.CallOption) (*Int64, error) {
	out := new(Int64)
	err := grpc.Invoke(ctx, "/go_grpc_eg.Greeter/CalculateCube", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeter service

type GreeterServer interface {
	CalculateSquare(context.Context, *Int64) (*Int64, error)
	CalculateCube(context.Context, *Int64) (*Int64, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_CalculateSquare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Int64)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).CalculateSquare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go_grpc_eg.Greeter/CalculateSquare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).CalculateSquare(ctx, req.(*Int64))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_CalculateCube_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Int64)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).CalculateCube(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go_grpc_eg.Greeter/CalculateCube",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).CalculateCube(ctx, req.(*Int64))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go_grpc_eg.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateSquare",
			Handler:    _Greeter_CalculateSquare_Handler,
		},
		{
			MethodName: "CalculateCube",
			Handler:    _Greeter_CalculateCube_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "go_grpc_eg.proto",
}

func init() { proto.RegisterFile("go_grpc_eg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 132 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xcf, 0x8f, 0x4f,
	0x2f, 0x2a, 0x48, 0x8e, 0x4f, 0x4d, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x42, 0x88,
	0x28, 0xc9, 0x72, 0xb1, 0x7a, 0xe6, 0x95, 0x98, 0x99, 0x08, 0x89, 0x70, 0xb1, 0x96, 0x25, 0xe6,
	0x94, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07, 0x41, 0x38, 0x46, 0xb5, 0x5c, 0xec, 0xee,
	0x45, 0xa9, 0xa9, 0x25, 0xa9, 0x45, 0x42, 0x96, 0x5c, 0xfc, 0xce, 0x89, 0x39, 0xc9, 0xa5, 0x39,
	0x89, 0x25, 0xa9, 0xc1, 0x85, 0xa5, 0x89, 0x45, 0xa9, 0x42, 0x82, 0x7a, 0x48, 0x66, 0x83, 0x8d,
	0x91, 0xc2, 0x14, 0x52, 0x62, 0x10, 0x32, 0xe7, 0xe2, 0x85, 0x6b, 0x75, 0x2e, 0x4d, 0x22, 0x5a,
	0x63, 0x12, 0x1b, 0xd8, 0xc1, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x75, 0x85, 0x7f,
	0xc4, 0x00, 0x00, 0x00,
}
